version: '{build}'
image:
- Visual Studio 2017
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
init:
- cmd: dotnet --info
build_script:
- ps: build.ps1
test: off
deploy: off
